In [1]:
import numpy as np

### 1D-array

In [2]:
p = np.array([42, 55, 50]) # 1D-array / Vector
p

array([42, 55, 50])

In [3]:
aa = np.array([5, 6 ,1 ,8])
bb = np.array([16, 19, 50, 100, 11, 3])
cc = np.concatenate((aa, bb))
cc

array([  5,   6,   1,   8,  16,  19,  50, 100,  11,   3])

In [4]:
np.sort(cc)

array([  1,   3,   5,   6,   8,  11,  16,  19,  50, 100])

In [5]:
np.sort(p)

array([42, 50, 55])

In [6]:
type(p)

numpy.ndarray

In [7]:
len(p)

3

In [8]:
p[0]

42

In [9]:
res = np.array([1, 2, 3, 4, 5, 6]) # array
res

array([1, 2, 3, 4, 5, 6])

In [10]:
a = np.zeros(2) # for zeroes 0's
a

array([0., 0.])

In [11]:
b = np.ones(3) # for ones 1's
b

array([1., 1., 1.])

In [12]:
c = np.empty(5) # empty
c

array([0., 0., 0., 0., 0.])

In [13]:
d = np.arange(9) # range to (9)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
e = np.arange(1, 56) # range b/w (1 to 56)
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55])

In [15]:
f = np.arange(0, 30, 3) # range with difference 3's b/w (0 to 30)
f

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [16]:
g = np.linspace(2, 20, num=10) # lineraly spaced array
g

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [17]:
h = np.ones(5, dtype=np.int8) # choose specific- dataType
h

array([1, 1, 1, 1, 1], dtype=int8)

In [18]:
i = np.ones(4, dtype=np.float16) # choose specific- dataType
i

array([1., 1., 1., 1.], dtype=float16)

---

---

---

### 2D-array

In [19]:
r = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # 2d-array 
r

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
type(r)

numpy.ndarray

In [21]:
len(r)

3

In [22]:
r[2]

array([7, 8, 9])

In [23]:
x = np.zeros([2,3])
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
xx = np.ones([3,2])
xx

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
y = np.empty([3,3])
y

array([[nan,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [26]:
k = np.array([5, 6 ,1 ,8])
j = np.array([16, 19, 50, 100, 11, 3])
pp = np.concatenate([k, j])
pp

array([  5,   6,   1,   8,  16,  19,  50, 100,  11,   3])

---

---

---

### 3D-array

In [27]:
dd = np.arange(45).reshape(3,5,3)
dd

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [28]:
ddd = np.arange(24).reshape(4,2,3)
ddd

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [29]:
t = np.arange(30).reshape(5,2,3)
t

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])