In [1]:
import numpy as np

---

## ***1D-array***. (Vector Array)

In [2]:
food = np.array(["pizza", "burger", "roll"])
food

array(['pizza', 'burger', 'roll'], dtype='<U6')

In [69]:
food.ndim

1

In [3]:
type(food)

numpy.ndarray

In [1]:
len(food)

NameError: name 'food' is not defined

In [5]:
food[1]

'burger'

In [6]:
food[1:]

array(['burger', 'roll'], dtype='<U6')

---

---

In [7]:
number = np.array([42, 55, 47, 50, 26])
number

array([42, 55, 47, 50, 26])

In [8]:
type(number)

numpy.ndarray

In [9]:
len(number)

5

In [10]:
number[3]

50

In [11]:
number[2:]

array([47, 50, 26])

In [12]:
number.mean() # mean method !

44.0

In [13]:
np.zeros(4)  # zeroes method !

array([0., 0., 0., 0.])

In [14]:
np.ones(6) # ones method !

array([1., 1., 1., 1., 1., 1.])

In [15]:
np.empty(3)

array([1.35545154e-311, 0.00000000e+000, 5.39198933e+067])

#### ***arange method*** !

In [16]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(5,55,5) # table of (5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [19]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [20]:
np.sort(number)

array([26, 42, 47, 50, 55])

---

### Array-Functions

In [21]:
a = np.array([5, 6, 9, 50, 1, 30, 24, 14, 2, 42, 26]) # integer array
a

array([ 5,  6,  9, 50,  1, 30, 24, 14,  2, 42, 26])

In [68]:
a.ndim

2

In [22]:
b = np.array([14.1, 13.5, 35.1, 2.71, 3.05, 26.4, 42.7, 18.3, 40.4, 10.2]) # floating-point array
b

array([14.1 , 13.5 , 35.1 ,  2.71,  3.05, 26.4 , 42.7 , 18.3 , 40.4 ,
       10.2 ])

In [23]:
a.sort()
a

array([ 1,  2,  5,  6,  9, 14, 24, 26, 30, 42, 50])

In [24]:
b.sort()
b

array([ 2.71,  3.05, 10.2 , 13.5 , 14.1 , 18.3 , 26.4 , 35.1 , 40.4 ,
       42.7 ])

In [25]:
c = np.concatenate([a,b])
c

array([ 1.  ,  2.  ,  5.  ,  6.  ,  9.  , 14.  , 24.  , 26.  , 30.  ,
       42.  , 50.  ,  2.71,  3.05, 10.2 , 13.5 , 14.1 , 18.3 , 26.4 ,
       35.1 , 40.4 , 42.7 ])

In [26]:
np.sort(c)

array([ 1.  ,  2.  ,  2.71,  3.05,  5.  ,  6.  ,  9.  , 10.2 , 13.5 ,
       14.  , 14.1 , 18.3 , 24.  , 26.  , 26.4 , 30.  , 35.1 , 40.4 ,
       42.  , 42.7 , 50.  ])

In [67]:
c.ndim

2

---

---

---

## ***2D-array***. (Matrix Array)

In [57]:
a = np.array([[1,2,2],[3,5,3],[11,22,33]])
a

array([[ 1,  2,  2],
       [ 3,  5,  3],
       [11, 22, 33]])

In [58]:
b = np.array([[4,6,4],[5,2,3],[2,3,5]])
b

array([[4, 6, 4],
       [5, 2, 3],
       [2, 3, 5]])

In [59]:
c = np.concatenate([a,b], axis=0) # Length would be same !
c

array([[ 1,  2,  2],
       [ 3,  5,  3],
       [11, 22, 33],
       [ 4,  6,  4],
       [ 5,  2,  3],
       [ 2,  3,  5]])

In [61]:
d = np.concatenate([a,b], axis=1) # Length would be same !
d

array([[ 1,  2,  2,  4,  6,  4],
       [ 3,  5,  3,  5,  2,  3],
       [11, 22, 33,  2,  3,  5]])

In [66]:
d.ndim

2

In [110]:
np.reshape(d, newshape=(1,18), order='C')

array([[ 1,  2,  2,  4,  6,  4,  3,  5,  3,  5,  2,  3, 11, 22, 33,  2,
         3,  5]])

---

---

## ***3D-array***. (Tensor Array)

In [75]:
x = np.array([[[1,2],[3,4]],
             [[5,6],[7,8]],
             [[9,1],[4,8]]])
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 1],
        [4, 8]]])

In [77]:
x.ndim

3

In [80]:
type(x)

numpy.ndarray

In [82]:
np.size(x)

12

In [87]:
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 1],
        [4, 8]]])

In [88]:
x.shape

(3, 2, 2)

In [73]:
y = np.array([[[9,8],[7,6]],
             [[5,4],[3,2]],
             [[1,2],[4,3]]])
y

array([[[9, 8],
        [7, 6]],

       [[5, 4],
        [3, 2]],

       [[1, 2],
        [4, 3]]])

In [78]:
y.ndim

3

In [79]:
type(y)

numpy.ndarray

In [83]:
np.size(y)

12

In [86]:
y

array([[[9, 8],
        [7, 6]],

       [[5, 4],
        [3, 2]],

       [[1, 2],
        [4, 3]]])

In [85]:
y.shape

(3, 2, 2)

#### ***arange method*** !

In [97]:
a = np.arange(27) # arange [27]
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [99]:
t = a.reshape(3,3,3) # reshape = [3*3*3 = 27]
t

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

---

In [96]:
t = np.arange(27).reshape(3,3,3)
t

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

---

---

---

***convert 1D-array to 2D-array***

In [112]:
u = np.array([5,6,8,9,4,3,2])
u

array([5, 6, 8, 9, 4, 3, 2])

In [129]:
u[2:5]

array([8, 9, 4])

In [130]:
u[:6]

array([5, 6, 8, 9, 4, 3])

In [131]:
u[1:]

array([6, 8, 9, 4, 3, 2])

In [122]:
u.sum()

37

In [123]:
u.mean()

5.285714285714286

In [127]:
u*2

array([10, 12, 16, 18,  8,  6,  4])

In [128]:
u+1

array([ 6,  7,  9, 10,  5,  4,  3])

In [113]:
u.shape

(7,)

In [119]:
u.ndim

1

In [117]:
# row-wise (2D)
o = u[np.newaxis, :]
o

array([[5, 6, 8, 9, 4, 3, 2]])

In [121]:
# columns-wise (2D)
o = u[:, np.newaxis]
o

array([[5],
       [6],
       [8],
       [9],
       [4],
       [3],
       [2]])

In [118]:
o.shape

(1, 7)

In [120]:
o.ndim

2