### <span style="color:orange">Step: 00</span>: (Import Libraries)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### <span style="color:orange">Step: 01</span>: (Import Dataset)

In [2]:
df = pd.read_csv('company.csv')
df.head(1)

Company_Name  Coding  Year  ESG Score  Return on Equity  Return on Asset  \
0   HOME DEPOT       1  2008      65.85             12.74             6.24   

   Earning Per Share  Price/Sales Per Share Ratio  \
0               1.34                         0.54   

   Earning before Interest & Taxes  DIVIDEND_YIELD  
0                            4.214            3.54

### <span style="color:orange">Step: 02</span>: Data Cleaning

In [3]:
df.isnull().sum()

Company_Name                       0
Coding                             0
Year                               0
ESG Score                          0
Return on Equity                   0
Return on Asset                    0
Earning Per Share                  0
Price/Sales Per Share Ratio        0
Earning before Interest & Taxes    0
DIVIDEND_YIELD                     0
dtype: int64

In [4]:
# import encodeing library !
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Company_Name'] = le.fit_transform(df['Company_Name'])

In [5]:
df[['Company_Name']].head()

Company_Name
0            51
1            51
2            51
3            51
4            51

In [6]:
# transformation !
from sklearn.preprocessing import MinMaxScaler

feature = [i for i in df.columns if i not in ['ESG Score', 'Year']]
# feature = X.columns
scaling = MinMaxScaler()
df[feature] = scaling.fit_transform(df[feature])

In [7]:
X = df
y = df[['ESG Score']]

In [8]:
X.head(2)

Company_Name  Coding  Year  ESG Score  Return on Equity  Return on Asset  \
0      0.515152     0.0  2008      65.85          0.008042         0.600927   
1      0.515152     0.0  2009      53.06          0.008153         0.620041   

   Earning Per Share  Price/Sales Per Share Ratio  \
0           0.613446                     0.038168   
1           0.617318                     0.053435   

   Earning before Interest & Taxes  DIVIDEND_YIELD  
0                         0.248056        0.200113  
1                         0.251298        0.232335

In [9]:
y.head(2)

ESG Score
0      65.85
1      53.06

### <span style="color:orange">Step: 03</span>: Splitting Dataset into (Training and Testing) Data 

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### <span style="color:orange">Step: 04</span>: Apply Techniques !

### <span style="color:blue">(KNN).K-Nearest_Neighbor</span>

In [11]:
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor()
knn.fit(X_train, y_train)


KNeighborsRegressor()

---

In [12]:
predicted_values = knn.predict(X_test)
predicted_values


array([[63.494],
       [53.42 ],
       [68.67 ],
       [69.744],
       [55.316],
       [65.426],
       [43.282],
       [86.724],
       [69.434],
       [38.164],
       [55.332],
       [72.104],
       [48.458],
       [59.962],
       [46.636],
       [41.618],
       [77.052],
       [68.05 ],
       [59.284],
       [83.532],
       [58.128],
       [67.664],
       [58.186],
       [77.1  ],
       [69.322],
       [58.014],
       [69.534],
       [50.942],
       [84.426],
       [47.788],
       [54.124],
       [57.602],
       [68.864],
       [48.918],
       [63.122],
       [62.478],
       [64.232],
       [65.652],
       [56.776],
       [58.408],
       [57.93 ],
       [42.24 ],
       [60.496],
       [36.366],
       [69.162],
       [64.082],
       [62.864],
       [42.754],
       [75.02 ],
       [44.564],
       [44.738],
       [28.   ],
       [51.304],
       [78.954],
       [71.866],
       [46.928],
       [46.894],
       [75.812],
       [67.576

In [13]:
# find mae
from sklearn.metrics import mean_absolute_error

knn_mae = mean_absolute_error(y_test, predicted_values)
knn_mae


0.23853846153846114

In [14]:
# find rmse
from sklearn.metrics import mean_squared_error
from math import sqrt

knn_rmse = sqrt(mean_squared_error(y_test, predicted_values))
knn_rmse


0.3348823444366463

---

---

### <span style="color:blue">Polynomial Regression</span>

In [15]:
from sklearn.linear_model import LinearRegression

reg_line = LinearRegression()
reg_line.fit(X_train, y_train)


LinearRegression()

---

In [16]:
predicted_values = reg_line.predict(X_test)
predicted_values


array([[63.08],
       [53.47],
       [68.53],
       [70.11],
       [55.22],
       [65.16],
       [43.23],
       [87.89],
       [69.49],
       [38.06],
       [55.27],
       [72.37],
       [48.47],
       [59.8 ],
       [46.72],
       [41.65],
       [76.41],
       [67.95],
       [59.2 ],
       [83.19],
       [58.48],
       [67.62],
       [58.04],
       [77.09],
       [69.09],
       [58.02],
       [69.31],
       [50.67],
       [83.58],
       [47.87],
       [53.94],
       [57.09],
       [68.43],
       [48.84],
       [63.01],
       [62.13],
       [64.06],
       [65.36],
       [56.71],
       [58.52],
       [57.84],
       [42.07],
       [60.6 ],
       [35.89],
       [69.01],
       [63.94],
       [63.36],
       [42.91],
       [74.43],
       [44.67],
       [44.89],
       [28.07],
       [51.43],
       [79.36],
       [71.8 ],
       [46.64],
       [46.63],
       [75.52],
       [67.44],
       [39.85],
       [31.92],
       [55.73],
       [

In [17]:
# find mae
from sklearn.metrics import mean_absolute_error

reg_mae = mean_absolute_error(y_test, predicted_values)
reg_mae


2.4800674334703496e-15

In [18]:
# find rmse
from sklearn.metrics import mean_squared_error
from math import sqrt

reg_rmse = sqrt(mean_squared_error(y_test, predicted_values))
reg_rmse


4.17610993224481e-15

---

---

### <span style="color:blue">Decision Tree</span>

In [19]:
from sklearn.tree import DecisionTreeRegressor 

dtree = DecisionTreeRegressor()
dtree.fit(X_train, y_train)


DecisionTreeRegressor()

---

In [20]:
predicted_values = dtree.predict(X_test)
predicted_values


array([63.08, 53.58, 68.43, 70.08, 55.18, 65.19, 43.31, 87.72, 69.51,
       38.09, 55.32, 72.53, 48.52, 59.7 , 46.69, 41.67, 76.32, 68.05,
       59.02, 83.09, 58.47, 67.68, 58.02, 77.11, 69.11, 58.02, 69.27,
       50.73, 83.6 , 47.84, 53.92, 57.05, 68.43, 48.89, 63.12, 62.14,
       64.13, 65.33, 56.73, 58.5 , 57.84, 42.1 , 60.64, 35.63, 69.11,
       63.91, 63.4 , 43.04, 74.43, 44.74, 44.8 , 27.5 , 51.47, 79.38,
       71.78, 46.69, 46.74, 75.56, 67.68, 39.58, 31.85, 55.91, 60.48,
       56.16, 39.63, 71.78, 43.92, 30.29, 50.48, 10.6 , 85.67, 46.45,
       77.44, 62.09, 40.27, 67.68, 39.63, 58.02, 58.97, 68.08, 57.05,
       73.18, 71.56, 74.09, 69.27, 61.49, 33.12, 44.67, 48.57, 71.05,
       30.66, 49.54, 66.74, 58.85, 48.8 , 56.  , 68.4 , 26.49, 65.54,
       72.2 , 57.05, 69.39, 62.9 , 53.05, 67.16, 10.6 , 71.1 , 51.85,
       80.75, 48.52, 38.82, 66.94, 56.67, 47.73, 46.26, 50.48, 42.28,
       54.  , 77.04, 45.29, 67.68, 39.05, 65.54, 25.89, 67.42, 53.88,
       76.32, 30.7 ,

In [21]:
# find mae
from sklearn.metrics import mean_absolute_error

dtree_mae = mean_absolute_error(y_test, predicted_values)
dtree_mae


0.16319230769230783

In [22]:
# find rmse
from sklearn.metrics import mean_squared_error
from math import sqrt

dtree_rmse = sqrt(mean_squared_error(y_test, predicted_values))
dtree_rmse


0.6310470542007028

---

---

### <span style="color:blue">Random Forest</span>

In [23]:
from sklearn.ensemble import RandomForestRegressor

rforest = RandomForestRegressor()
rforest.fit(X_train, y_train)


C:\Users\fahad\AppData\Local\Temp/ipykernel_3792/4138979454.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rforest.fit(X_train, y_train)


RandomForestRegressor()

---

In [24]:
predicted_values = rforest.predict(X_test)
predicted_values


array([63.0898, 53.6185, 68.5027, 70.1148, 55.1513, 65.1841, 43.2151,
       87.7515, 69.469 , 38.053 , 55.3356, 72.4976, 48.515 , 59.7888,
       46.7193, 41.6722, 76.3064, 68.0785, 59.2923, 83.2177, 58.4663,
       67.6272, 57.9804, 77.0583, 69.1217, 58.012 , 69.263 , 50.7315,
       83.7196, 47.8295, 53.9091, 57.0613, 68.4347, 48.8779, 63.0551,
       62.1574, 64.0641, 65.3391, 56.7003, 58.506 , 57.8469, 42.0674,
       60.633 , 35.6563, 69.0714, 63.904 , 63.3542, 42.9101, 74.4201,
       44.6616, 44.8845, 27.9721, 51.447 , 79.3774, 71.7763, 46.6922,
       46.687 , 75.5242, 67.4418, 39.5958, 31.9682, 55.7202, 60.4815,
       56.0457, 39.5558, 71.7871, 43.96  , 30.3906, 50.4945, 15.9683,
       85.4998, 46.3732, 77.4632, 62.0838, 40.2074, 67.3479, 39.5415,
       58.0007, 58.9593, 68.0941, 57.0689, 73.2114, 71.5843, 73.9728,
       69.2131, 61.603 , 33.2564, 44.6679, 48.5859, 70.963 , 30.1109,
       49.5329, 66.9033, 58.8488, 48.8657, 56.2483, 68.3897, 26.3531,
       65.5665, 72.1

In [25]:
# find mae
from sklearn.metrics import mean_absolute_error

rforest_mae = mean_absolute_error(y_test, predicted_values)
rforest_mae


0.0729642307692308

In [26]:
# find rmse
from sklearn.metrics import mean_squared_error
from math import sqrt

rforest_rmse = sqrt(mean_squared_error(y_test, predicted_values))
rforest_rmse


0.20398015071230632

---

---

### <span style="color:blue">SVM Linear</span>

In [27]:
from sklearn import svm

support_linear = svm.SVR(kernel= 'linear')
support_linear.fit(X_train, y_train)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVR(kernel='linear')

---

In [28]:
predicted_values = support_linear.predict(X_test)
predicted_values


array([63.04042522, 53.44189891, 68.47385157, 70.05006296, 55.19529139,
       65.12031697, 43.23576422, 87.78988325, 69.437696  , 38.07055595,
       55.24206181, 72.31133378, 48.46351669, 59.76867007, 46.71855282,
       41.6568281 , 76.3426736 , 67.90227924, 59.16565894, 83.1014113 ,
       58.45669063, 67.57258056, 58.0046205 , 77.02212766, 69.0299747 ,
       57.99937941, 69.25799488, 50.65608392, 83.49451416, 47.86353806,
       53.92093954, 57.06604777, 68.38211547, 48.82751953, 62.96437823,
       62.09561664, 64.01735274, 65.31012111, 56.68549673, 58.48567574,
       57.80760074, 42.07486531, 60.5689382 , 35.92172034, 68.96302778,
       63.88755435, 63.31709416, 42.91242634, 74.35620429, 44.66540457,
       44.89389933, 28.10494872, 51.41230021, 79.28808747, 71.74491101,
       46.62792797, 46.6344557 , 75.44860415, 67.38307177, 39.85497903,
       31.9535339 , 55.70901101, 60.41073411, 56.16099734, 39.58243612,
       71.74699206, 43.93181008, 30.21583442, 50.5858241 , 18.12

In [29]:
# find mae
from sklearn.metrics import mean_absolute_error

support_linear_mae = mean_absolute_error(y_test, predicted_values)
support_linear_mae


0.03276526382972508

In [30]:
# find rmse
from sklearn.metrics import mean_squared_error
from math import sqrt

support_linear_rmse = sqrt(mean_squared_error(y_test, predicted_values))
support_linear_rmse


0.04003558426934226

***

***

### <span style="color:blue">SVM RFB</span>

In [31]:
from sklearn import svm

support_RBF = svm.SVR(kernel= 'rbf')
support_RBF.fit(X_train, y_train)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVR()

---

In [32]:
predicted_values = support_RBF.predict(X_test)
predicted_values


array([54.31959045, 54.24177038, 54.36038648, 54.37199246, 54.25744822,
       54.33782577, 54.1657829 , 54.50924555, 54.37056431, 54.12324519,
       54.25729407, 54.39214176, 54.20608831, 54.29492294, 54.19430553,
       54.15252461, 54.42321258, 54.35816061, 54.28862792, 54.47368008,
       54.28699409, 54.35617756, 54.27859439, 54.42900792, 54.36359239,
       54.28345192, 54.36862596, 54.22302555, 54.47890019, 54.20147134,
       54.24928118, 54.27407925, 54.36240437, 54.20725858, 54.31682531,
       54.31394723, 54.32713549, 54.33489006, 54.27058371, 54.2822878 ,
       54.27704362, 54.15575715, 54.30218994, 54.11268246, 54.3679852 ,
       54.32231408, 54.32120017, 54.16220729, 54.40465641, 54.17408252,
       54.17965944, 54.04754006, 54.22830409, 54.44700788, 54.38889447,
       54.18923208, 54.19527872, 54.41415398, 54.35090037, 54.13756215,
       54.0793555 , 54.26417196, 54.3015108 , 54.26492854, 54.13706943,
       54.3894468 , 54.17061162, 54.06542898, 54.22248481, 53.96

In [33]:
# find mae
from sklearn.metrics import mean_absolute_error

support_RBF_mae = mean_absolute_error(y_test, predicted_values)
support_RBF_mae


12.763734776993918

In [34]:
# find rmse
from sklearn.metrics import mean_squared_error
from math import sqrt

support_RBF_rmse = sqrt(mean_squared_error(y_test, predicted_values))
support_RBF_rmse


15.307956959469331

***

***

In [35]:
data={'KNN(K_Nearest_Neighbour)'   :[knn_mae, knn_rmse],
      'LinearRegression'           :[reg_mae, reg_rmse],
        'Decesion Tree'            :[dtree_mae, dtree_rmse],
        'Random Forest'            :[rforest_mae, rforest_rmse],
            "SVM (Linear)"         :[support_linear_mae, support_linear_rmse],
               "SVM (RBF)"         :[support_RBF_mae, support_RBF_rmse]
}

In [36]:
Evaluation =pd.DataFrame(data, index=['SCORE'])
Evaluation

ValueError: Shape of passed values is (2, 6), indices imply (1, 6)