### <span style="color:orange">Step: 00</span>: (Import Libraries)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### <span style="color:orange">Step: 01</span>: (Import Dataset)

In [2]:
df = pd.read_csv('company.csv')
df.head(1)

Company_Name  Coding  Year  ESG Score  Return on Equity  Return on Asset  \
0   HOME DEPOT       1  2008      65.85             12.74             6.24   

   Earning Per Share  Price/Sales Per Share Ratio  \
0               1.34                         0.54   

   Earning before Interest & Taxes  DIVIDEND_YIELD  
0                            4.214            3.54

### <span style="color:orange">Step: 02</span>: Data Cleaning

In [3]:
df.isnull().sum()

Company_Name                       0
Coding                             0
Year                               0
ESG Score                          0
Return on Equity                   0
Return on Asset                    0
Earning Per Share                  0
Price/Sales Per Share Ratio        0
Earning before Interest & Taxes    0
DIVIDEND_YIELD                     0
dtype: int64

In [4]:
# import encodeing library !
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Company_Name'] = le.fit_transform(df['Company_Name'])

In [5]:
df[['Company_Name']].head(2)

Company_Name
0            51
1            51

In [6]:
# transformation !
from sklearn.preprocessing import MinMaxScaler

feature = [i for i in df.columns if i not in ['ESG Score', 'Year']]
# feature = X.columns
scaling = MinMaxScaler()
df[feature] = scaling.fit_transform(df[feature])

In [7]:
X = df
y = df[['ESG Score']]

In [8]:
X.head(2)

Company_Name  Coding  Year  ESG Score  Return on Equity  Return on Asset  \
0      0.515152     0.0  2008      65.85          0.008042         0.600927   
1      0.515152     0.0  2009      53.06          0.008153         0.620041   

   Earning Per Share  Price/Sales Per Share Ratio  \
0           0.613446                     0.038168   
1           0.617318                     0.053435   

   Earning before Interest & Taxes  DIVIDEND_YIELD  
0                         0.248056        0.200113  
1                         0.251298        0.232335

In [9]:
y.head(2)

ESG Score
0      65.85
1      53.06

### <span style="color:orange">Step: 03</span>: Splitting Dataset into (Training and Testing) Data 

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### <span style="color:orange">Step: 04</span>: Apply Techniques !

### <span style="color:blue">(KNN).K-Nearest_Neighbor</span>

In [11]:
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor()
knn.fit(X_train, y_train)


KNeighborsRegressor()

---

In [12]:
predicted_values = knn.predict(X_test)
predicted_values


array([[63.494],
       [53.42 ],
       [68.67 ],
       [69.744],
       [55.316],
       [65.426],
       [43.282],
       [86.724],
       [69.434],
       [38.164],
       [55.332],
       [72.104],
       [48.458],
       [59.962],
       [46.636],
       [41.618],
       [77.052],
       [68.05 ],
       [59.284],
       [83.532],
       [58.128],
       [67.664],
       [58.186],
       [77.1  ],
       [69.322],
       [58.014],
       [69.534],
       [50.942],
       [84.426],
       [47.788],
       [54.124],
       [57.602],
       [68.864],
       [48.918],
       [63.122],
       [62.478],
       [64.232],
       [65.652],
       [56.776],
       [58.408],
       [57.93 ],
       [42.24 ],
       [60.496],
       [36.366],
       [69.162],
       [64.082],
       [62.864],
       [42.754],
       [75.02 ],
       [44.564],
       [44.738],
       [28.   ],
       [51.304],
       [78.954],
       [71.866],
       [46.928],
       [46.894],
       [75.812],
       [67.576

In [13]:
# find mae
from sklearn.metrics import mean_absolute_error

knn_mae = mean_absolute_error(y_test, predicted_values)
knn_mae


0.23853846153846114

In [14]:
# find rmse
from sklearn.metrics import mean_squared_error
from math import sqrt

knn_rmse = sqrt(mean_squared_error(y_test, predicted_values))
knn_rmse


0.3348823444366463

---

---

### <span style="color:blue">Polynomial Regression</span>

In [15]:
from sklearn.linear_model import LinearRegression

reg_line = LinearRegression()
reg_line.fit(X_train, y_train)


LinearRegression()

---

In [16]:
predicted_values = reg_line.predict(X_test)
predicted_values


array([[63.08],
       [53.47],
       [68.53],
       [70.11],
       [55.22],
       [65.16],
       [43.23],
       [87.89],
       [69.49],
       [38.06],
       [55.27],
       [72.37],
       [48.47],
       [59.8 ],
       [46.72],
       [41.65],
       [76.41],
       [67.95],
       [59.2 ],
       [83.19],
       [58.48],
       [67.62],
       [58.04],
       [77.09],
       [69.09],
       [58.02],
       [69.31],
       [50.67],
       [83.58],
       [47.87],
       [53.94],
       [57.09],
       [68.43],
       [48.84],
       [63.01],
       [62.13],
       [64.06],
       [65.36],
       [56.71],
       [58.52],
       [57.84],
       [42.07],
       [60.6 ],
       [35.89],
       [69.01],
       [63.94],
       [63.36],
       [42.91],
       [74.43],
       [44.67],
       [44.89],
       [28.07],
       [51.43],
       [79.36],
       [71.8 ],
       [46.64],
       [46.63],
       [75.52],
       [67.44],
       [39.85],
       [31.92],
       [55.73],
       [

In [17]:
# find mae
from sklearn.metrics import mean_absolute_error

reg_mae = mean_absolute_error(y_test, predicted_values)
reg_mae


2.4800674334703496e-15

In [18]:
# find rmse
from sklearn.metrics import mean_squared_error
from math import sqrt

reg_rmse = sqrt(mean_squared_error(y_test, predicted_values))
reg_rmse


4.17610993224481e-15

---

---

### <span style="color:blue">Decision Tree</span>

In [19]:
from sklearn.tree import DecisionTreeRegressor 

dtree = DecisionTreeRegressor()
dtree.fit(X_train, y_train)


DecisionTreeRegressor()

---

In [20]:
predicted_values = dtree.predict(X_test)
predicted_values


array([63.08, 53.58, 68.4 , 70.09, 55.14, 65.25, 43.31, 88.12, 69.51,
       38.04, 55.33, 72.53, 48.59, 59.7 , 46.74, 41.67, 76.33, 68.06,
       59.02, 83.03, 58.45, 67.63, 58.02, 77.08, 69.03, 58.02, 69.27,
       50.73, 83.6 , 47.83, 53.92, 57.05, 68.4 , 48.87, 63.12, 62.09,
       64.13, 65.36, 56.71, 58.47, 57.84, 42.1 , 60.64, 35.63, 69.03,
       63.91, 63.4 , 43.04, 74.43, 44.68, 44.8 , 27.42, 51.47, 79.27,
       71.75, 46.74, 46.69, 75.52, 67.53, 39.72, 31.85, 55.63, 60.52,
       56.16, 39.61, 71.78, 43.96, 30.29, 50.5 , 17.29, 85.48, 46.45,
       77.44, 62.09, 40.27, 67.53, 39.61, 58.02, 58.97, 68.09, 57.05,
       73.18, 71.58, 73.96, 69.27, 61.64, 33.12, 44.66, 48.59, 71.05,
       30.29, 49.56, 66.74, 58.85, 48.8 , 56.  , 68.4 , 26.49, 65.54,
       72.2 , 57.02, 69.39, 62.87, 53.05, 67.12, 16.17, 71.13, 51.99,
       80.72, 48.48, 38.74, 66.89, 56.67, 47.73, 46.26, 50.5 , 42.28,
       53.82, 77.  , 45.32, 67.68, 39.01, 65.54, 25.89, 67.63, 53.92,
       76.32, 30.7 ,

In [21]:
# find mae
from sklearn.metrics import mean_absolute_error

dtree_mae = mean_absolute_error(y_test, predicted_values)
dtree_mae


0.10480769230769234

In [22]:
# find rmse
from sklearn.metrics import mean_squared_error
from math import sqrt

dtree_rmse = sqrt(mean_squared_error(y_test, predicted_values))
dtree_rmse


0.18093453979908783

---

---

### <span style="color:blue">Random Forest</span>

In [23]:
from sklearn.ensemble import RandomForestRegressor

rforest = RandomForestRegressor()
rforest.fit(X_train, y_train)


C:\Users\fahad\AppData\Local\Temp/ipykernel_7872/4138979454.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rforest.fit(X_train, y_train)


RandomForestRegressor()

---

In [24]:
predicted_values = rforest.predict(X_test)
predicted_values


array([63.089 , 53.6333, 68.522 , 70.0962, 55.1393, 65.1754, 43.2066,
       87.6804, 69.4702, 38.0492, 55.3364, 72.5624, 48.5298, 59.7541,
       46.7063, 41.6716, 76.3497, 68.0887, 59.2941, 83.3031, 58.4583,
       67.625 , 57.9865, 77.0772, 69.1126, 58.0064, 69.275 , 50.7358,
       83.7648, 47.815 , 53.8864, 57.0471, 68.4376, 48.8799, 63.0492,
       62.1709, 64.0608, 65.3436, 56.689 , 58.509 , 57.843 , 42.069 ,
       60.604 , 35.6715, 69.0325, 63.9171, 63.3429, 42.9205, 74.4706,
       44.6726, 44.9017, 28.0525, 51.4391, 79.3827, 71.7874, 46.6961,
       46.6985, 75.5302, 67.396 , 39.6151, 31.9597, 55.7766, 60.4783,
       56.0623, 39.5787, 71.7848, 43.9586, 30.3942, 50.5064, 15.2855,
       85.4938, 46.3874, 77.4621, 62.0877, 40.206 , 67.3455, 39.5527,
       57.9951, 58.9584, 68.0962, 57.0377, 73.2151, 71.596 , 73.8983,
       69.2111, 61.5838, 33.2382, 44.6695, 48.584 , 70.9464, 30.1381,
       49.5422, 66.8689, 58.8388, 48.8771, 56.2643, 68.3586, 26.416 ,
       65.552 , 72.1

In [25]:
# find mae
from sklearn.metrics import mean_absolute_error

rforest_mae = mean_absolute_error(y_test, predicted_values)
rforest_mae


0.08279538461538714

In [26]:
# find rmse
from sklearn.metrics import mean_squared_error
from math import sqrt

rforest_rmse = sqrt(mean_squared_error(y_test, predicted_values))
rforest_rmse


0.25317089986501545

---

---

### <span style="color:blue">SVM Linear</span>

In [27]:
from sklearn import svm

support_linear = svm.SVR(kernel= 'linear')
support_linear.fit(X_train, y_train)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVR(kernel='linear')

---

In [28]:
predicted_values = support_linear.predict(X_test)
predicted_values


array([63.04042522, 53.44189891, 68.47385157, 70.05006296, 55.19529139,
       65.12031697, 43.23576422, 87.78988325, 69.437696  , 38.07055595,
       55.24206181, 72.31133378, 48.46351669, 59.76867007, 46.71855282,
       41.6568281 , 76.3426736 , 67.90227924, 59.16565894, 83.1014113 ,
       58.45669063, 67.57258056, 58.0046205 , 77.02212766, 69.0299747 ,
       57.99937941, 69.25799488, 50.65608392, 83.49451416, 47.86353806,
       53.92093954, 57.06604777, 68.38211547, 48.82751953, 62.96437823,
       62.09561664, 64.01735274, 65.31012111, 56.68549673, 58.48567574,
       57.80760074, 42.07486531, 60.5689382 , 35.92172034, 68.96302778,
       63.88755435, 63.31709416, 42.91242634, 74.35620429, 44.66540457,
       44.89389933, 28.10494872, 51.41230021, 79.28808747, 71.74491101,
       46.62792797, 46.6344557 , 75.44860415, 67.38307177, 39.85497903,
       31.9535339 , 55.70901101, 60.41073411, 56.16099734, 39.58243612,
       71.74699206, 43.93181008, 30.21583442, 50.5858241 , 18.12

In [29]:
# find mae
from sklearn.metrics import mean_absolute_error

support_linear_mae = mean_absolute_error(y_test, predicted_values)
support_linear_mae


0.03276526382972508

In [30]:
# find rmse
from sklearn.metrics import mean_squared_error
from math import sqrt

support_linear_rmse = sqrt(mean_squared_error(y_test, predicted_values))
support_linear_rmse


0.04003558426934226

***

***

### <span style="color:blue">SVM RFB</span>

In [31]:
from sklearn import svm

support_RBF = svm.SVR(kernel= 'rbf')
support_RBF.fit(X_train, y_train)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVR()

---

In [32]:
predicted_values = support_RBF.predict(X_test)
predicted_values


array([54.31959045, 54.24177038, 54.36038648, 54.37199246, 54.25744822,
       54.33782577, 54.1657829 , 54.50924555, 54.37056431, 54.12324519,
       54.25729407, 54.39214176, 54.20608831, 54.29492294, 54.19430553,
       54.15252461, 54.42321258, 54.35816061, 54.28862792, 54.47368008,
       54.28699409, 54.35617756, 54.27859439, 54.42900792, 54.36359239,
       54.28345192, 54.36862596, 54.22302555, 54.47890019, 54.20147134,
       54.24928118, 54.27407925, 54.36240437, 54.20725858, 54.31682531,
       54.31394723, 54.32713549, 54.33489006, 54.27058371, 54.2822878 ,
       54.27704362, 54.15575715, 54.30218994, 54.11268246, 54.3679852 ,
       54.32231408, 54.32120017, 54.16220729, 54.40465641, 54.17408252,
       54.17965944, 54.04754006, 54.22830409, 54.44700788, 54.38889447,
       54.18923208, 54.19527872, 54.41415398, 54.35090037, 54.13756215,
       54.0793555 , 54.26417196, 54.3015108 , 54.26492854, 54.13706943,
       54.3894468 , 54.17061162, 54.06542898, 54.22248481, 53.96

In [33]:
# find mae
from sklearn.metrics import mean_absolute_error

support_RBF_mae = mean_absolute_error(y_test, predicted_values)
support_RBF_mae


12.763734776993918

In [36]:
# find rmse
from sklearn.metrics import mean_squared_error
from math import sqrt

support_RBF_rmse = sqrt(mean_squared_error(y_test, predicted_values))
support_RBF_rmse


15.307956959469331

***

***

In [39]:
data={'KNN(K_Nearest_Neighbour)'   :[knn_mae, knn_rmse],
      'LinearRegression'           :[reg_mae, reg_rmse],
        'Decesion Tree'            :[dtree_mae, dtree_rmse],
        'Random Forest'            :[rforest_mae, rforest_rmse],
            "SVM (Linear)"         :[support_linear_mae, support_linear_rmse],
               "SVM (RBF)"         :[support_RBF_mae, support_RBF_rmse]
}

NameError: name 'support_RBF_mae' is not defined